title: <p align="center"> Johannes Kilian Langer </p>

logo: "/images/picture.png?raw=true"

description: <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jklanger/">LinkedIn</a> |
  <a href="https://github.com/jklanger">GitHub</a>
  </p>

  <p align="justify">
  I am a data scientist with strong theoretical background in applied mathematics, statistics and machine learning.
  <br><br>
  I have extensive knowledge in software development with 10+ years of programming experience and as data scientist & scrum master with 4+ years of work experience.
  <br><br>
  I am focused on improving the management of real world processes with software solutions, from digitalisation to human decision making.
  <br><br>
  </p>

theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
